name: DirtyArrows
main: nl.SugCube.DirtyArrows.DirtyArrows
version: '2.6'
description: >
             DirtyArrows, just dirty
commands:
  da:
    description: DirtyArrows
    permission: dirtyarrows
  dirtyarrows:
    description: DirtyArrows
    permission: dirtyarrows