name: DirtyArrows
main: nl.sugcube.dirtyarrows.DirtyArrows
version: '4.0'
description: >
             DirtyArrows, just dirty
commands:
  da:
    description: DirtyArrows
    permission: dirtyarrows
  dirtyarrows:
    description: DirtyArrows
    permission: dirtyarrows